### ISSUE TITLE
Startup issue w/ Add-on

### ISSUE THREAD

**Issue by yieldhog** [jdeath/RTLAMR2MQQT#1]
Hi -- I have a RTL-SDR Blog V3 R820T2 RTL2832U 1PPM TCXO HF Bias Tee SMA Software Defined Radio with Dipole Antenna Kit ([Link](https://www.amazon.com/gp/product/B011HVUEME/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1))

Running Hassio 0.107.4 on an Intel NUC w/ Ubuntu. I have previously installed rtl_tcp using apt-get.. looks like it is detecting my device.

I installed your add-on, however I am getting the following error after it starts. Any thoughts much appreciated.

`main.go:85: Error connecting to spectrum server: dial tcp 127.0.0.1:1234: connect: connection refused
rcvr.Connect
main.(*Receiver).NewReceiver
	/go/src/github.com/bemasher/rtlamr/main.go:85
main.main
	/go/src/github.com/bemasher/rtlamr/main.go:325
runtime.main
	/usr/lib/go/src/runtime/proc.go:203
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1357`

**Comment by jdeath** [comment]
No sorry, I don't know why. I now use that same device, after my mini died
somehow. I only used a pi, never tested on ubuntu, but don't think it would
be different.

Looks like rtl_tcp may not be running. Look in the rtl2mqtt.sh script which
should be in \\HASSIO\config\rtlamr2mqtt\

perhaps remove the /dev/null and the & to look at the output. The line
should then look like this:
/usr/local/bin/rtl_tcp

See if there is output in the logs.

If that does work, comment out the

/go/bin/rtlamr  line in the loop below. then docker exec into the container
and play around with running  rtlamr manually

Sorry, I am no expert with this.
