### ISSUE TITLE
High Values with Mosquito Broker Update

### ISSUE THREAD

**Issue by esmoyer** [jdeath/RTLAMR2MQQT#13]
I think this might be an issue more with Mosquito Broker as whenever it updates all of my utility meter readings go sky high for one reading then go back to normal right after the update and the add-on starts. I wanted to check here if this happens to anyone else and is there a way to prevent this?

**Comment by jdeath** [comment]
I have never had this problem. As a test. perhaps try cpyarger's new version of my addon. He bypasses mqtt and uses homeassistant's api directly. No need to setup manual mqtt sensors.  You can easily switch between the two, but need to configure his separately and the sensor names will be different.

https://github.com/cpyarger/Home-Assistant-Addons

**Comment by esmoyer** [comment]
Oh nice, was not aware of that. I will check it out. Thanks!
