### ISSUE TITLE
Error on start - s6-overlay-suexec: fatal: can only run as pid 1

### ISSUE THREAD

**Issue by FSTGuy** [jdeath/RTLAMR2MQQT#14]
Hi,

Thanks again for the great add-on that worked flawlessly. I was able to receive my gas and water meter readings. Unfortunately, I recently upgrade my home assistant instance. Now I receive a "s6-overlay-suexec: fatal: can only run as pid 1" error In the logs and the add-on won't start.

I have removed and reinstalled, unplugged and plugged back in the dongle, restarted HA and I still encountered the Issue. Do you have any thoughts?

Home Assistant Core 2022.5.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.1
Kernel version 5.15.41
Agent version 1.2.1

**Comment by jdeath** [comment]
Looks like there was a breaking change to homeassistant addons!
https://developers.home-assistant.io/blog/2022/05/12/s6-overlay-base-images/

Seems like an easy fix, which I'll try to do shortly. Thanks for identifying.

**Comment by FSTGuy** [comment]
Thanks for investigating! I saw the article but was not sure how to implement so I thought I would ask the Professional:)

**Comment by jdeath** [comment]
Just posted a fix. Please try it out.

**Comment by FSTGuy** [comment]
Your update works perfectly on 2022.5.5. I upgraded to 2022.6.0 to test and it also works. Thanks again for fixing the issue! Awesome add-on, great work!
