### ISSUE TITLE
Failed to install add-on error - returned a non-zero code: 1

### ISSUE THREAD

**Issue by FSTGuy** [jdeath/RTLAMR2MQQT#15]
Hi, your software was working great until I upgraded home assistant. I upgraded to latest version and when I attempt to install the add-on I receive the error below. 
I would in be interested in your thoughts.

System Information
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.05.3
Home Assistant OS 8.2

Error message attempting to install
"Failed to install add-on
The command '/bin/ash -o pipefail -c go get github.com/bemasher/rtlamr' returned a non-zero code: 1"

**Comment by jdeath** [comment]
yup. Golang actually changed how it works, so I need to do some fixes. Hopefully won't take long to fix. the issue only creeps up if you rebuild the addon

**Comment by jdeath** [comment]
ok. 0.53 should fix. If rebuilding doesn't work, I would recommend copying your configuration to a text file, completely uninstall addon, install addon, and then copy back your configuration. report back and let me know if works

**Comment by FSTGuy** [comment]
Hi, Thanks for fixing this, it is working! I really appreciate it! Great work it really help me with the Gas and Water meter readings in Home Assistant. Keep up the great work!
