### ISSUE TITLE
Addon is unable to find the 

### ISSUE THREAD

**Issue by biochemguy** [jdeath/RTLAMR2MQQT#4]
Hi, 

Thanks for making this available for all. 

Not sure if it is a bug in the addon or my OS, but I am in the process of migrating to HassOS and tried your add-on. I am running the 64 bit version of HassOS. After installing the addon and placing the file in the proper location /config/rtlamr2mqtt/rtl2mqtt.sh with the added line for the 64 bit version, the program still cannot find the rtl2mqtt.sh file. Any ideas?

Here is the log info:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/bin/ash: /rtl2mqtt.sh: not found
[cmd] /bin/ash exited 127
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

Any help is appreciated.

**Comment by jdeath** [comment]
That is strange. I can look at code tonight to see what happens if the file
is not there.

 Can you confirm the file is there from an ssh terminal shell? Sometimes
the samba add on gets stuck and not really there.

**Comment by biochemguy** [comment]
Yes, the file is available with ssh and samba, and I can open it with a text editor. 

I don't think that this is the problem, but I don't know if it matters where I place the 64 bit line `export LD_LIBRARY_PATH=/usr/local/lib64,` but I simply placed it above the `export LANG=C` line. 

Trying to think, I also added the addon via the the addon store by linking it to your repo and ran it from there. I don't think that should be the issue either?

**Comment by jdeath** [comment]
It should not matter where the LD_LIBRARY_PATH line is. The error for not
having that line would not show up until after the rtl2mqtt.sh is run. I
also run it now from the addon store now too.

When I remove the file from /config/rtlamr2mqtt/rtl2mqtt.sh I get this
error:

cp: cannot stat '/config/rtlamr2mqtt/rtl2mqtt.sh': No such file or directory

So I think it is copying the file. Can you try to remove the file, and
see if you get the same error as me. Then it must be the "chmod +x
/rtl2mqtt.sh && /rtl2mqtt.sh" which is not being executed from the
docker file.

If that does not work, try "rebuilding" the addon, instead of just
restarting it.

Let me know

**Comment by biochemguy** [comment]
So, I have figured it out. Since you told me that the problem was maybe with the rtl2mqtt.sh file, I remembered that when I copied the code for the rtl2mqtt.sh, I copied the raw data from github and pasted it in a .txt file and simply renamed it. I think that the coding from the basic text editor had modified the file formatting. I simply copied the file from github instead and added the 64 bit line and replaced it in the folder and it works.

Thanks a lot for your help!

**Comment by biochemguy** [comment]
Hi,

Now that it passes the rtl2mqtt.sh file I get an other error (Not sure if I should have opened a new issue or not for this). I am guessing that it is related to sending the data to the MQTT server, but I am not sure. I can successfully pass other things to the MQTT server, but so far I am unable to receive the data from the rtl2mqtt. 

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> Starting RTLAMR with parameters:
> MQTT Host = 192.168.1.10:1883
> MQTT User = xxxxxx
> MQTT Password = xxxxxx
> MQTT Message Type = scm
> MQTT Device IDs = 12345678,2346789
> 11:00:32.719260 decode.go:45: CenterFreq: 912600155
> 11:00:32.719971 decode.go:46: SampleRate: 2359296
> 11:00:32.720004 decode.go:47: DataRate: 32768
> 11:00:32.720028 decode.go:48: ChipLength: 72
> 11:00:32.720050 decode.go:49: PreambleSymbols: 21
> 11:00:32.720084 decode.go:50: PreambleLength: 3024
> 11:00:32.720107 decode.go:51: PacketSymbols: 96
> 11:00:32.720129 decode.go:52: PacketLength: 13824
> 11:00:32.720158 decode.go:59: Protocols: scm
> 11:00:32.720253 decode.go:60: Preambles: 111110010101001100000
> 11:00:32.720282 main.go:119: GainCount: 29
> Unable to connect (Lookup error.).
> Unable to connect (Lookup error.).
> Unable to connect (Lookup error.).

I tried reinstalling or rebuilding the addon and changing the port of this MQTT client 1883, 1884, 8883, as my server listens to them. 

Any ideas?

**Comment by jdeath** [comment]
Looks I neglected to have an mqqt port setting. Did you change the port of
your sever or just in my add on settings? I don’t think the latter will
work. I assumed everyone used the default.

Two ways to check:
1. In the shell script, remove/comment out the line that has the
mosquito-pub (starts with an echo). If you no longer get an error, then
 that is the issue.

2. Add the line back in,and add the correct argument for a different port.
I can try update the add on over the weekend.

**Comment by biochemguy** [comment]
I am using the default ports for the mqtt server. I just assumed that I needed to map the port in the mqtt host settings in the config files. I removed the port mapping in the configuration and simply pointed it to the server IP address and I can now receive the meter readings.

Thanks a lot again!
