### ISSUE TITLE
Start-up issue after recent Home Assistant upgrade

### ISSUE THREAD

**Issue by yieldhog** [jdeath/RTLAMR2MQQT#5]
Had been working great, recently upgraded Home Assistant -- now receiving errors, thanks

core-2021.2.2
supervisor-2021.02.6

Getting following errors in log, add-on crashes after startup.

WARNING (MainThread) [supervisor.addons.validate] Add-on config 'startup' with 'before' is deprecated. Please report this to the maintainer of RTLAMR to MQTT Bridge

WARNING (MainThread) [supervisor.addons.validate] Add-on config 'devices' use a deprecated format, the new format uses a list of paths only. Please report this to the maintainer of RTLAMR to MQTT Bridge

Following error for the add-on:

07:24:52.917561 main.go:85: Error connecting to spectrum server: dial tcp 127.0.0.1:1234: connect: connection refused
rcvr.Connect
main.(*Receiver).NewReceiver
	/go/src/github.com/bemasher/rtlamr/main.go:85
main.main
	/go/src/github.com/bemasher/rtlamr/main.go:325
runtime.main
	/usr/lib/go/src/runtime/proc.go:204
runtime.goexit
	/usr/lib/go/src/runtime/asm_amd64.s:1374

**Comment by yieldhog** [comment]
Appears per https://developers.home-assistant.io/docs/add-ons/configuration/ that config.json should be updated to a new format.

"startup": "application"

I'm not sure what to do with the new devices format

**Comment by jdeath** [comment]
I saw the warnings. I was going to look at it too. I've poked around to fix
the devices, but not sure what to do. I think it's just a Json list, but
haven't found a good example.

Mine still works, those are just warnings for now. Probably be a while
until needs to be fixed.

Did you recently switch to a 64 bit version? there is a library path you
need to add. Also, does your setup list the actual IP address of your mqtt
server? Localhost, hassio.local, etc may not work anymore. Needs the
192.168.x.x format.

**Comment by yieldhog** [comment]
Hm. I made no changes, had been working great for a few months, already had the 64 bit library path in the sh file I also have the mqtt in 192 format. It broke after upgrading to core-2021.2.2 and then supervisor-2021.02.6 yesterday.. tried rebooting and still throwing errors.

**Comment by jdeath** [comment]
Argh. I was running fine on those versions, but I never restarted the
addon. When I restarted the addon, I now get the same error as you. I will
try to look into it over the next couple days.

**Comment by jdeath** [comment]
Can you try the new version I pushed to github. Just do a refresh of the
addons. I don't think you need to rebuild the addon. All I changed was the
config.json

**Comment by yieldhog** [comment]
@jdeath -- legend, appears to be back up and running. Thanks!
