### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by staraxis** [jdeath/RTLAMR2MQQT#7]
Thanks for the great addon!

I was wondering if it was possible to implement this library (https://github.com/merbanan/rtl_433) as the James Fry addon did. I had it working quite well with my efergy power monitor but that addon no longer plays nice with the Supervisor. 

I'm happy to help out in anyway I can.

Cheers

**Comment by jdeath** [comment]
I think there is another 433 addon that might work for you

https://community.home-assistant.io/t/home-assistant-add-on-rtl-433-with-mqtt-auto-discovery/260665

Your old addon will probably work with a couple adjustments, if you want to
keep it. The supervisor recently changed how usb devices are specified. Look at the
config.Json file in James' addon. 
Remove the 
"devices": ["/dev/bus/usb:/dev/bus/usb:rwm"],

 add replace it with
 “usb”: true,

Also change startup from "before" to "application"

You can download his GitHub code into your /addon directory and make the changes there.
