### ISSUE TITLE
No MQTT Message Crossing

### ISSUE THREAD

**Issue by esmoyer** [jdeath/RTLAMR2MQQT#8]
I had this setup and running smooth but woke up this morning to no updated data overnight. I have been checking everything but configuration is right; nothing was changed. I manually checked the SDR and I am receiving signals/messages; it just seems like they aren't crossing from the add-on to the MQTT broker. Looking at MQTT Fx, I am not seeing any message cross. Credentials in the add-on are correct, logs all look good. The only thing I see off is: "Socket error on client <unknown>, disconnecting." in the Mosquitto Broker logs. I can't seem to figure it out and it's driving me crazy. Any insight?

**Comment by jdeath** [comment]
No insight. Your diagnostic skills are much better than mine. Did you reboot the host? Ensure you are using the full IP address of the mqtt broker, localhost/127.0.0.1 sometimes does not work. Echo some of the value in the rtl2mqtt.sh script to be sure everything is correct. Those are my only tips

**Comment by esmoyer** [comment]
Thanks for the response. I still have no clue what the deal was. I am thinking something happened with the MQTT broker? No clue. Not an issue anymore since I just got done migrating to use Proxmox instead of Windows and VirtualBox. Fingers crossed this remains stable!
