### ISSUE TITLE
i/o timeout

### ISSUE THREAD

**Issue by esmoyer** [jdeath/RTLAMR2MQQT#9]
Sorry, another question as I am trying to learn the ins and outs of this: The add-on will be running great for hours or days but sometimes it will randomly show this in the logs:
```
read tcp 127.0.0.1:45698->127.0.0.1:1234: i/o timeout
io.ReadFull
```
Any clue what this means? I have tried Googling around but nothing overly helpful in relation to SDRs. I'm on a Proxmox VM with HAOS with plenty of resources. Restarting the AddOn doesn't do anything, the error just comes back, but restarting the whole VM usually fixes it. Not sure if it's losing connection to the dongle maybe?

**Comment by jdeath** [comment]
Do you use the -duration tag that I documented? This where you read in values for a time, then have a delay, and repeat. The error you showed happens at the end of the -duration interval
`/go/bin/rtlamr -format json -msgtype=$MQTT_MSGTYPE -filterid=$MQTT_IDS -duration=60s | while read line
`
If not, it is probably losing connection. That is why it is in a loop to reestablish a connection.

**Comment by esmoyer** [comment]
Indeed I do! I'll remove that and see how it goes. I guess i wasn't sure if there are any downsides to just letting it run. I'll give it a go, thanks again!

**Comment by esmoyer** [comment]
It appears removing the -duration flag has done the trick. Been stable for a couple days now (knock on wood) Thanks again!
